### ISSUE TITLE
メディア情報学部、情報システム学科リンク修正

### ISSUE THREAD

**Issue by g2072018** [tcu-seki-lab/hp#41]
ヘッダー部分の学部・学科リンクの修正
※研究室概要、教授紹介、活動報告の各ページ
文字列　|　挿入リンク
- メディア情報学部　|　https://informatics.tcu.ac.jp/
- 情報システム学科　|　https://informatics.tcu.ac.jp/faculty/system/

**Comment by totchin** [comment]
completed
